import Link from 'next/link';

export default function HomePage() {
  return <main className="landing">
    <nav className="landing-nav"><Link className="brand" href="/">CODEX<span>FLOW</span></Link><div><Link href="/app">Open dashboard</Link><Link className="button" href="/app">Start with GitHub</Link></div></nav>
    <section className="landing-hero"><p className="eyebrow">AI ENGINEERING CONTROL PLANE</p><h1>AI coding agents.<br /><em>Under control.</em></h1><p>CodexFlow plans, executes, reviews, verifies, and delivers AI-assisted changes through isolated worktrees and human approval—before anything reaches GitHub.</p><div className="actions"><Link className="button" href="/app">Start with GitHub</Link><Link className="button secondary" href="/app#local-project">Open a local project</Link></div></section>
    <section className="pipeline-preview" aria-label="CodexFlow workflow"><div className="preview-head"><span>CONTROLLED DELIVERY</span><span className="status status-passed">VERIFIED</span></div><div className="preview-flow">{['Task','Plan','Code','Review','Test','Repair','Approve','GitHub PR'].map((step, index) => <div className="preview-stage" key={step}><b>0{index + 1}</b><span>{step}</span></div>)}</div><div className="preview-foot"><span>isolated worktree</span><span>backend approval</span><span>SHA reconciled</span></div></section>
    <section className="landing-section"><p className="eyebrow">WHY CODEXFLOW</p><h2>Agents can write code. They should not control delivery.</h2><div className="feature-grid"><article><h3>Isolated by default</h3><p>Every task runs in its own Git worktree. Your primary checkout and protected branches stay protected.</p></article><article><h3>Verification is evidence</h3><p>Tests, lint, typechecks, and builds are actual commands with persisted results—not model claims.</p></article><article><h3>Approval stays human</h3><p>Risk and diff fingerprints are server-derived. Delivery does not begin until an approved workspace is revalidated.</p></article><article><h3>GitHub-native delivery</h3><p>Commit, remote branch, and PR head SHAs must agree before a delivery is considered valid.</p></article><article><h3>Durable execution</h3><p>Lifecycle state, agent runs, delivery checkpoints, and recovery evidence are persisted in SQLite.</p></article><article><h3>Provenance you can inspect</h3><p>Strategies, specialist outcomes, repair attempts, and evaluation records remain traceable after a run completes.</p></article></div></section>
    <section className="landing-section workflow-section"><p className="eyebrow">WORKFLOW</p><h2>From repository to verified pull request.</h2><ol>{['Connect a GitHub repository or open a local Git project.','Describe the change in your own words.','CodexFlow plans and executes inside an isolated workspace.','Inspect review, verification, risk, and repair evidence.','Approve the exact diff.','Create and reconcile the GitHub pull request.'].map((step, index) => <li key={step}><b>0{index + 1}</b><span>{step}</span></li>)}</ol></section>
    <section className="landing-cta"><p className="eyebrow">READY TO WORK</p><h2>Your agents can write the code.<br />CodexFlow controls what reaches GitHub.</h2><div className="actions"><Link className="button" href="/app">Start with GitHub</Link><Link className="button secondary" href="/app#local-project">Open a local project</Link></div></section>
    <footer><strong>CODEX<span>FLOW</span></strong><div><Link href="/app">Product</Link><Link href="/docs/demo.md">Documentation</Link><a href="https://github.com" target="_blank" rel="noreferrer">GitHub</a></div></footer>
  </main>;
}
